#!/bin/bash
#(C) 	Kirils Solovjovs, 2015
dir="$HOME/scripts/records.tty" #where to store records
max_replay_time=300

if [ -z "$*" ]; then
	echo -n "Session name (filename): "
	read name
else
	name="$*"
fi
filename="$(date +%Y-%m-%d)"
[ ! -z "$name" ] && filename="${filename}_${name}"
filename="${filename}_$$.ttyrec"
[ -e "$dir/$filename" ] && echo "Sorry, will not overwrite an existing file." && exit 1
echo "Recording to $filename..."
t_start="$(date +%s)"
ttyrec -e "/bin/bash --rcfile <(echo \" PS1='\[\033[01;32m\]user@host\[\033[01;34m\] \w \\\\$\[\033[00m\] '\") -i" -- "$dir/$filename"
t_end="$(date +%s)"
speed="$(echo  $(echo \($t_end - $t_start \)/$max_replay_time | bc -l) $'\n'3|sort -nr|head -1)"
size="$(($(cat -- "$dir/$filename" | wc -c ) / 1000))"
echo -e "Recording saved to $filename ($size KB).\nAuto-replay in 3 seconds: ^C to cancel"
sleep 3
reset
ttyplay -s $speed -- "$dir/$filename"
echo "ttyarec exiting..."
