#!/bin/bash
#(C) 	Kirils Solovjovs, 2015
dir="$HOME/scripts/records.tty" #where to store records

if [ -z "$*" ]; then
	echo -n "Session name (filename): "
	read name
else
	name="$*"
fi
filename="$(date +%Y-%m-%d)_$$"
[ ! -z "$name" ] && filename="${filename}_${name}"
filename="$filename.ttyrec"
[ -e "$dir/$filename" ] && echo "Sorry, will not overwrite an existing file." && exit 1
echo "Recording to $filename..."
ttyrec -e "env PS1='\[\033[01;32m\]user@host\[\033[01;34m\] \w \$\[\033[00m\] ' /bin/bash --norc -i" -- "$dir/$filename"
size="$(($(cat -- "$dir/$filename" | wc -c ) / 1000))"
echo -e "Recording saved to $filename ($size KB).\nAuto-replay in 3 seconds: ^C to cancel"
sleep 3
reset
ttyplay -- "$dir/$filename"
echo "ttyarec exiting..."
